### ISSUE TITLE
can we change tmpdir on windows?

### ISSUE THREAD

**Issue by t5n** [marlam/msmtp-mirror#19]
I'm new to C/C++ and  just compiled msmtp.exe to use as a PHP sendmail replacement on Windows, using MXE on CentOS 7. Though the executable works just fine in Powershell, it seems versions 1.8+ are returning "cannot create temporary file: Permission denied" when executing via PHP (sendmail_path=C:\path\to\msmtp.exe -t).

I believe this is due to the tmpfile() function in C/C++ trying to save temp files either to a restricted system folder (e.g. C:\Windows, source [1](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/tmpfile) [2](https://en.cppreference.com/w/cpp/io/c/tmpfile)) or an obscure nested folder in C:\Users\\<username>\AppData (source [3](https://stackoverflow.com/questions/16485031/where-does-tmpfile-store-the-files-it-creates-in-mingw-gcc-windows-7)).
However, despite my best efforts, I am not able to clear this error or find where the temp files are being deposited.
I tried changing the system environment variables TMP, TEMP, & TMPDIR, as well as the shotgun approach of granting Windows user rights to likely folders - all to no avail.

As such, I wonder whether there is a way to change the directory where these temp files are saved on Windows, for instance, at compilation. Having it set to C:\Windows\Temp would be nice, as this was the default location for temp files in v1.6.8 and earlier.

Any input would be very appreciated. Thank you.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/42794593/81771781-e9bfba00-94b1-11ea-89a3-2bf143945ad4.png">

**Comment by marlam** [comment]
Yes, this problem came up before, but I don't have a Windows system and therefore cannot test myself. Can you add the following three lines to src/tools.h at line 67 and check if it works?
`#ifdef W32_NATIVE`
`#define tmpfile() fopen(tmpnam(NULL), "w+bTD")`
`#endif`
With this, temporary files should be created in the system default directory for that purpose (and you can override this by setting the TMP environment variable). I have absolutely no idea why `tmpfile()` does not do this by default on Windows.

**Comment by marlam** [comment]
Update: I just pushed a patch that is an improved version of the above (with complete error checking, avoiding of race conditions, and a workaround for `tmpnam()` stupidity on Windows). Please try the latest version from the git repository to see if this fixes the problem.

**Comment by t5n** [comment]
Thank you much for the fast turnaround - I rebuilt the exe off the latest version and it's working just fine now. This tool is a great complement to PHP - esp. on Windows stacks - for setting up encrypted relay using modern TLS protocols, and it's very reassuring to be able to get support for Windows-only issues such as this. Thanks again.

**Comment by t5n** [comment]
Hi, just FYI seeing the error again running the new version in our staging system, even though TMP, TEMP, and TMPDIR are set to the same path (C:\Windows\Temp) and the service account already has "modify" rights to this folder.
After some digging, I confirmed the executable is indeed writing the temp file to CWD. In our PHP use case (where we configure msmtp.exe in php.ini), the CWD during execution often points to a code folder, which often shouldn't be writeable.

Here are two posts that also report this behavior: [1](https://stackoverflow.com/questions/38868858/fopen-of-file-name-created-by-tmpnam-fails-on-mingw) [2](https://stackoverflow.com/questions/18570517/c-tmpnam-alternative/18570757)

For WIN32, I wonder if it make sense to fetch the environment variable "TEMP" or "TMP" and designate this path explicitly in which to store temp files. Some related posts:
[3](https://exceptionshub.com/accessing-environment-variables-in-c.html) [4](https://stackoverflow.com/questions/1322442/getting-user-temporary-folder-path-in-windows) [5](https://techunravel.blogspot.com/2011/08/win32-env-variable-pitfall-of.html) [6](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getenvironmentvariable) [7](https://www.zachburlingame.com/2011/06/creating-temporary-files-on-win32-in-c-part-1/) [8](https://www.zachburlingame.com/2011/06/creating-temporary-files-on-win32-in-c-part-2/)

Or, is there any chance we'd be able to specify the tmp file path either at compile time or in the msmtprc.txt config file?

Thanks for your consideration.

**Comment by marlam** [comment]
Thanks for testing this. So according to your links, tmpnam() is broken on MinGW. That is unfortunate. I replaced it with a combination of GetTempPath() and _tempnam(), which should now work as intended: it uses either TMP, TEMP, USERPROFILE, or the Windows directory (in that order) for temporary files.
I can only test this with WINE, can you test on a real Windows machine?

**Comment by t5n** [comment]
The latest changes now seem to work both locally and on Azure, but I'm still seeing some inconsistencies monitoring the supposed paths fetched by GetTempPath(), between running as myself vs. running as the PHP user (despite identical TMP/TEMP vars).
For instance, when I run - either via web app (i.e. as the PHP user) on the last version or via command line (i.e. as myself) on this version - I actually see the TMP2/3/4 files get created and the mod date of the folder change as well, but when I run via web app on the current version, I don't see any such changes in the TMP folder, which seems to imply it's writing to a different path.
Before closing the issue, to make sure there are no final "gotchas," do you have any suggestions on a quick edit to either log the path returned by GetTempPath() or print it to stdout? Thanks so much for your advice.

**Comment by t5n** [comment]
Never mind; I added a simple "printf" to the w32_tmpfile function, recompiled, and confirmed after checking stdout that it is indeed writing to the directory corresponding to the TMP environment variable. Much appreciated!

**Comment by marlam** [comment]
OK, then the new version seems to fix the problem. This will be included in the next version of msmtp (and mpop too). Thanks for testing and verifying!

**Comment by t5n** [comment]
Hi Martin, looking at the _w32_tmpfile_ function, I'm wondering: 

If it can't open the file, due to the Race Condition of another call occupying this same file between (1) name generation and (2) creation, does this new function just return NULL (thus the "cannot create temporary file: Permission denied" again) instead of re-trying?

If so, would you consider looping the name generation/creation process a fixed (perhaps [TMP_MAX](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/1ea1hft7(v=vs.120))) number of times, to make it more robust to multiple threads (common in web servers)?

One solution is suggested below:

> Fundamentally, to create a temporary file in a shared (sticky) directory, you must repetitively: (1) create a “random” filename, (2) open it using O_CREAT | O_EXCL and very narrow permissions (which atomically creates the file and fails if it’s not created), and (3) stop repeating when the open succeeds. ([Source](https://dwheeler.com/secure-programs/Secure-Programs-HOWTO/avoid-race.html))
>
```
char *filename;
 int fd;

 do {
   filename = tempnam (NULL, "foo");
   fd = open (filename, O_CREAT | O_EXCL | O_TRUNC | O_RDWR, 0600);
   free (filename);
 } while (fd == -1);
```
Thanks for considering.

**Comment by marlam** [comment]
Good point, thanks for suggesting that. I pushed a patch that does this (but also limits the number of tries to TMP_MAX, in case open() fails repeatedly for different reasons).

Furthermore, I added a patch that uses different prefixes on different processes (not always "tmp", but something that depends on the process id). This should reduce the chances of name clashes between different instances of msmtp considerably, so the loop you proposed will likely run very few times, most likely just once.
